<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
    <?php header('Access-Control-Allow-Origin: *'); ?>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Tourgeni.us</title>

    <!-- Bootstrap Core CSS -->
    <link href="http://netdna.bootstrapcdn.com/bootstrap/3.0.3/css/bootstrap.min.css" rel="stylesheet" type="text/css">

    <!-- Fonts -->
    <link href="http://netdna.bootstrapcdn.com/font-awesome/4.0.3/css/font-awesome.min.css" rel="stylesheet" type="text/css">
    <link href='http://fonts.googleapis.com/css?family=Lora:400,700,400italic,700italic' rel='stylesheet' type='text/css'>
    <link href='http://fonts.googleapis.com/css?family=Montserrat:400,700' rel='stylesheet' type='text/css'>

    <!-- Custom Theme CSS -->
    <link href="css/lib/grayscale.css" rel="stylesheet">
	<link href="css/lib/chromeless.css" rel="stylesheet">
	<link href="css/lib/datepicker.css" rel="stylesheet" type="text/css" media="screen">
	
	<!-- Custom Theme Scripts -->
	
	
	<!-- Core JavaScript Files -->
    <script src="https://code.jquery.com/jquery-latest.js"></script>
    <script src="http://netdna.bootstrapcdn.com/bootstrap/3.1.0/css/bootstrap.min.css"></script>
    <script src="http://cdnjs.cloudflare.com/ajax/libs/jquery-easing/1.3/jquery.easing.min.js"></script>

</head>
<?php echo $this->layout()->content; ?>
</html>
